[build]
  base    = "client"
  command = "echo 'DEBUG: Listing files...' && ls -R client/src/components && echo '--- DEBUG: Footer.tsx content ---' && cat client/src/components/shared/Footer.tsx | head -n 15 && echo '--- DEBUG: End of debug ---' && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
